# action.yml
name: 'Github Pages Directory Listing (simple html fork)'
description: 'Github Action to generate simplified html directory listing index for Github Pages'

author: 'dieseltravis'
branding:
  color: 'blue'
  icon: 'upload-cloud'

inputs:
  FOLDER:
    description: 'folder to start index generations'
    required: true
  FILE_DATES:
    description: '! delimited list of filename|date pairs'
    required: true
  DO_RSS:
    description: 'generate RSS feed'
    required: false
  DO_ATOM:
    description: 'todo: generate Atom feed'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.FOLDER }}
    - ${{ inputs.FILE_DATES }}
    - ${{ inputs.DO_RSS }}
    - ${{ inputs.DO_ATOM }}
