# action.yml
name: 'Github Pages Directory Listing (simple html fork)'
description: 'Github Action to generate simplified html directory listing index for Github Pages'

author: 'dieseltravis'
branding:
  color: 'blue'
  icon: 'upload-cloud'

inputs:
  FOLDER:
    description: 'folder to start index generations'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.FOLDER }}
    - ${{ inputs.GIF_DATES }}
